# Generated by Django 4.0.4 on 2022-06-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombreProduc', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion Producto')),
                ('sku', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Codigo Pproducto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
